language: node_js
node_js:
  - "12"  # Specify the Node.js version

services:
  - docker  # Enable Docker service

before_install:
  - docker --version  # Ensure Docker is installed

after_success:
  # Log in to Docker Hub using credentials stored in Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build Docker image
  - docker build -t udagram-api-feed ./udagram-api-feed
  # Push both the latest and the commit-specific tags to Docker Hub
  - docker push $DOCKER_USERNAME/udagram-api-feed

# Only deploy from the main branch
branches:
  only:
    - main
